default: &default
    class: 'DFM'
    ratio_th: [1., 1., 1., 1.,1.]
    fine_ratio: 0.95
    model: 'resnet18'
    fine_model: 'r2d2'
    up_sample: [16, 1]
    two_stage: True
    bidirectional: True
    fine_weights_path: "/remote-home/zwlong/image-matching-toolbox/third_party/DFM/models/off-the-shelf/R2D2/dstl_r2d2.pt"
    #fine_weights_path: "/remote-home/zwlong/image-matching-toolbox/third_party/DFM/models/off-the-shelf/R2D2/r2d2_WASF_N16.pt"
    
   
hpatch:
    <<: *default
    match_threshold: 0.0
    imsize: -1
megadepth:
    <<: *default
    imsize: 1200
scannet:
    <<: *default
    imsize: 480
yfcc:
    <<: *default
    match_threshold: 0.0
    imsize: 1600
